"""fix

Revision ID: 09848858a4fc
Revises: 58b122b37abe
Create Date: 2025-11-16 15:48:34.633385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09848858a4fc'
down_revision: Union[str, Sequence[str], None] = '58b122b37abe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lead',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'lead',
               existing_type=sa.String(length=255),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
