"""first migrations

Revision ID: 58b122b37abe
Revises: 
Create Date: 2025-11-14 23:40:19.128383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b122b37abe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('language', sa.Enum('EN', 'UA', 'RU', name='language'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_action', sa.DateTime(), nullable=True),
    sa.Column('lead', sa.Boolean(), nullable=True),
    sa.Column('avg_budget', sa.Float(), nullable=True),
    sa.Column('reason_decline', sa.String(length=255), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requested_apartments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('district_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('microarea_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('street_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('condition_in', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('rooms_in', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('price_min', sa.Float(), nullable=True),
    sa.Column('price_max', sa.Float(), nullable=True),
    sa.Column('area_min', sa.Float(), nullable=True),
    sa.Column('area_max', sa.Float(), nullable=True),
    sa.Column('floor_min', sa.Integer(), nullable=True),
    sa.Column('floor_max', sa.Integer(), nullable=True),
    sa.Column('floors_total_max', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('appartment_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('replies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('reply', sa.String(length=2555), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('replies')
    op.drop_table('requested_apartments')
    op.drop_table('messages')
    op.drop_table('users')
    # ### end Alembic commands ###
