"""fix

Revision ID: 8791b1b37388
Revises: 5c2e8be50b6b
Create Date: 2025-11-16 17:15:56.651540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8791b1b37388'
down_revision: Union[str, Sequence[str], None] = '5c2e8be50b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('context_msg_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('context_reply_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'context_reply_id')
    op.drop_column('users', 'context_msg_id')
    # ### end Alembic commands ###
